apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  
spec:
  project: default
  destination:
    #namespace: development
    server: https://kubernetes.default.svc
  
  source:
    repoURL: https://github.com/technbd/argocd-demo.git
    path: kustomize-yamls
    targetRevision: HEAD
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
